---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-multicast
  labels:
    app: python-multicast
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-multicast
  template:
    metadata:
      labels:
        app: python-multicast
      annotations:
        #k8s.v1.cni.cncf.io/networks: weave
        k8s.v1.cni.cncf.io/networks: myipvlan
        #k8s.v1.cni.cncf.io/networks: mymacvlan
    spec:
      containers:
      - name: python-multicast
        image: georgenicoll/python-multicast:latest
        command: ["sleep","infinity"]
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "10m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
