apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-multicast
  labels:
    app: python-multicast
spec:
  replicas: 10
  selector:
    matchLabels:
      app: python-multicast
  template:
    metadata:
      labels:
        app: python-multicast
      annotations:
        k8s.v1.cni.cncf.io/networks: l3-bridge@mc0
    spec:
      containers:
      - name: python-multicast
        image: georgenicoll/python-multicast:latest
        command: ["sleep","infinity"]
        ports:
        - containerPort: 80   
      hostNetwork: false 
